# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

before_script:
  # Install JFrog CLI
  - wget https://dl.bintray.com/jfrog/jfrog-cli-go/1.12.1/jfrog-cli-linux-amd64/jfrog
  - chmod +x jfrog
  # Configure Artifactory instance with JFrog CLI
  - ./jfrog rt config --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASS
  - ./jfrog rt c show
  # Configure Npm client to fetch packages from Artifactory
  - npm config set registry $ARTIFACTORY_NPM_REPOSITORY
  - curl -u$ARTIFACTORY_USER:$ARTIFACTORY_PASS $ARTIFACTORY_URL/api/npm/auth >> ~/.npmrc
  - cat ~/.npmrc

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

build:
    script:
    - npm install -ddd
    - npm publish --registry $ARTIFACTORY_NPM_REPOSITORY -ddd
    # Collect build environment variables and build tools information using JFrog CLI
    - ./jfrog rt bce gitlabci-npm-artifactory $CI_JOB_ID
    # Publish build information to Artifactory
    - ./jfrog rt bp gitlabci-npm-artifactory $CI_JOB_ID
    only:
    - master
