# This file is a template, and might need editing before it works on your project.
image: python:latest

before_script:
  # Print out python version for debugging
  - python -V
  - ./gitlabci-credential.sh
  - pip install -r requirements.txt
  # Install JFrog CLI
  - wget https://dl.bintray.com/jfrog/jfrog-cli-go/1.12.1/jfrog-cli-linux-amd64/jfrog
  - chmod +x jfrog
  # Configure Artifactory instance with JFrog CLI
  - ./jfrog rt config --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASS
  - ./jfrog rt c show

build:
    script:
    - python setup.py sdist upload -r local
    - python setup.py bdist_wheel upload -r local
    # Collect build environment variables and build tools information using JFrog CLI
    - ./jfrog rt bce gitlabci-python-artifactory $CI_JOB_ID
    # Publish build information to Artifactory
    - ./jfrog rt bp gitlabci-python-artifactory $CI_JOB_ID
